import { seedId } from './ids.js';
import type { SeedPrismaClient, ShopItemSeedRow } from './types.js';

/** Authored from the ShopItem schema shape (sku/name/description/itemType/price/unlockDay/
 * isActive/iconImageUrl) directly — not copied from the frontend's hardcoded mock catalog in
 * src/frontend/src/components/Wall/mockBooks.js. */
export const SHOP_ITEMS: ShopItemSeedRow[] = [
  {
    id: seedId('03', 1),
    sku: 'EQ-DERMATOSCOPE',
    name: 'Dermatoscope',
    description: 'Magnified, polarized-light view of a lesion for pattern analysis.',
    itemType: 'EQUIPMENT',
    price: 150,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/equipment/dermatoscope.png',
  },
  {
    id: seedId('03', 2),
    sku: 'EQ-UV-WOODS-LAMP',
    name: "UV Wood's Lamp",
    description:
      'Ultraviolet light used to highlight pigmentation and some fungal/bacterial infections.',
    itemType: 'EQUIPMENT',
    price: 90,
    unlockDay: 2,
    isActive: true,
    iconImageUrl: '/icons/equipment/woods-lamp.png',
  },
  {
    id: seedId('03', 3),
    sku: 'EQ-DIGITAL-SKIN-CAMERA',
    name: 'Digital Skin Camera',
    description: 'High-resolution camera for consistent, comparable lesion photography over time.',
    itemType: 'EQUIPMENT',
    price: 200,
    unlockDay: 3,
    isActive: true,
    iconImageUrl: '/icons/equipment/skin-camera.png',
  },
  {
    id: seedId('03', 4),
    sku: 'EQ-MAGNIFYING-LOUPE',
    name: 'Magnifying Loupe',
    description: 'A simple handheld magnifier for closer visual inspection of borders and texture.',
    itemType: 'EQUIPMENT',
    price: 40,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/equipment/loupe.png',
  },
  {
    id: seedId('03', 5),
    sku: 'EQ-BIOPSY-PUNCH-KIT',
    name: 'Skin Biopsy Punch Kit',
    description: 'Sterile punch tools for taking a small tissue sample of an ambiguous lesion.',
    itemType: 'EQUIPMENT',
    price: 220,
    unlockDay: 5,
    isActive: true,
    iconImageUrl: '/icons/equipment/biopsy-kit.png',
  },
  {
    id: seedId('03', 6),
    sku: 'EQ-LESION-RULER',
    name: 'Lesion Measuring Ruler',
    description:
      'A clear millimeter ruler for objective lesion-diameter measurement (the "D" in ABCDE).',
    itemType: 'EQUIPMENT',
    price: 15,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/equipment/ruler.png',
  },
  {
    id: seedId('03', 7),
    sku: 'EQ-PORTABLE-EXAM-LIGHT',
    name: 'Portable Examination Light',
    description: 'Bright, adjustable lighting for a clearer view during exams.',
    itemType: 'EQUIPMENT',
    price: 60,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/equipment/exam-light.png',
  },
  {
    id: seedId('03', 8),
    sku: 'HB-CLINICAL-DERMATOLOGY-ATLAS',
    name: 'Clinical Dermatology Atlas',
    description: 'A broad photographic reference spanning common and uncommon skin presentations.',
    itemType: 'HANDBOOK',
    price: 80,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/handbooks/dermatology-atlas.png',
  },
  {
    id: seedId('03', 9),
    sku: 'HB-FIELD-GUIDE-COMMON-RASHES',
    name: 'Field Guide to Common Rashes',
    description:
      'Quick-reference guide for distinguishing frequently confused inflammatory rashes.',
    itemType: 'HANDBOOK',
    price: 45,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/handbooks/common-rashes.png',
  },
  {
    id: seedId('03', 10),
    sku: 'HB-MELANOMA-RECOGNITION-MANUAL',
    name: 'Melanoma Recognition Manual',
    description: 'Focused manual on early melanoma warning signs and lookalike benign lesions.',
    itemType: 'HANDBOOK',
    price: 100,
    unlockDay: 4,
    isActive: true,
    iconImageUrl: '/icons/handbooks/melanoma-manual.png',
  },
  {
    id: seedId('03', 11),
    sku: 'HB-PEDIATRIC-SKIN-CONDITIONS',
    name: 'Pediatric Skin Conditions Guide',
    description: 'Covers skin presentations and considerations specific to younger patients.',
    itemType: 'HANDBOOK',
    price: 55,
    unlockDay: 6,
    isActive: true,
    iconImageUrl: '/icons/handbooks/pediatric-guide.png',
  },
  {
    id: seedId('03', 12),
    sku: 'HB-INFECTIOUS-SKIN-DISEASE-REFERENCE',
    name: 'Infectious Skin Disease Reference',
    description: 'Reference on bacterial, viral, and fungal skin infections and their treatment.',
    itemType: 'HANDBOOK',
    price: 65,
    unlockDay: null,
    isActive: true,
    iconImageUrl: '/icons/handbooks/infectious-reference.png',
  },
  {
    id: seedId('03', 13),
    sku: 'HB-AUTOIMMUNE-SKIN-DISORDERS-PRIMER',
    name: 'Autoimmune Skin Disorders Primer',
    description:
      'Introductory primer on autoimmune-driven skin conditions like vitiligo and psoriasis.',
    itemType: 'HANDBOOK',
    price: 70,
    unlockDay: 8,
    isActive: true,
    iconImageUrl: '/icons/handbooks/autoimmune-primer.png',
  },
  {
    id: seedId('03', 14),
    sku: 'HB-PHOTOGRAPHIC-LESION-COMPARISON',
    name: 'Photographic Lesion Comparison Guide',
    description:
      'Side-by-side photo comparisons for judging whether a lesion has meaningfully changed.',
    itemType: 'HANDBOOK',
    price: 50,
    unlockDay: null,
    isActive: false,
    iconImageUrl: '/icons/handbooks/comparison-guide.png',
  },
  {
    id: seedId('03', 15),
    sku: 'PLOT-CLINIC-RENOVATION-PERMIT',
    name: 'Clinic Renovation Permit',
    description: 'Unlocks a renovated exam room later in the story.',
    itemType: 'PLOT_ITEM',
    price: 300,
    unlockDay: 10,
    isActive: true,
    iconImageUrl: null,
  },
  {
    id: seedId('03', 16),
    sku: 'PLOT-MALPRACTICE-INSURANCE-POLICY',
    name: 'Malpractice Insurance Policy',
    description: 'Reduces the money penalty for a future missed diagnosis.',
    itemType: 'PLOT_ITEM',
    price: 250,
    unlockDay: 7,
    isActive: true,
    iconImageUrl: null,
  },
  {
    id: seedId('03', 17),
    sku: 'PLOT-COMMUNITY-OUTREACH-FLYER',
    name: 'Community Outreach Flyer',
    description: 'Advertises the clinic locally, unlocking a future story beat.',
    itemType: 'PLOT_ITEM',
    price: 20,
    unlockDay: null,
    isActive: true,
    iconImageUrl: null,
  },
  {
    id: seedId('03', 18),
    sku: 'PLOT-RESEARCH-GRANT-CERTIFICATE',
    name: 'Research Grant Certificate',
    description: 'Represents funding secured for the clinic’s ongoing research subplot.',
    itemType: 'PLOT_ITEM',
    price: 400,
    unlockDay: 12,
    isActive: true,
    iconImageUrl: null,
  },
  {
    id: seedId('03', 19),
    sku: 'PLOT-CONTINUING-EDUCATION-CREDENTIAL',
    name: 'Continuing Education Credential',
    description: 'A completed certification, unlocking access to more advanced handbooks.',
    itemType: 'PLOT_ITEM',
    price: 180,
    unlockDay: 9,
    isActive: true,
    iconImageUrl: null,
  },
  {
    id: seedId('03', 20),
    sku: 'PLOT-CLINIC-SIGNAGE-UPGRADE',
    name: 'Clinic Signage Upgrade',
    description: 'A cosmetic upgrade to the clinic exterior; a purely flavor plot item.',
    itemType: 'PLOT_ITEM',
    price: 35,
    unlockDay: null,
    isActive: false,
    iconImageUrl: null,
  },
];

export async function seedShopItems(prisma: SeedPrismaClient): Promise<void> {
  for (const shopItem of SHOP_ITEMS) {
    const { id, ...update } = shopItem;
    await prisma.shopItem.upsert({ where: { id }, update, create: shopItem });
  }
}
